# Generated by Django 4.1.1 on 2022-09-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_autores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="ISBN",
            new_name="isbn",
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(default="sem email", max_length=254),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="editora",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="editora",
            name="site",
            field=models.URLField(null=True),
        ),
    ]
