# Generated by Django 4.1.1 on 2022-09-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_isbn_livro_isbn_alter_autor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
